POST http://localhost:8080/accounts
Content-Type: application/json

{
  "type": "SAVINGS",
  "balance": 1200.50
}

### Get account by ID
GET http://localhost:8080/accounts/999
Accept: application/json
### Update account
PUT http://localhost:8080/accounts/2
Content-Type: application/json

{
  "type": "SAVINGS",
  "balance": 9500.00
}

### Update account that doesn't exist
PUT http://localhost:8080/accounts/999
Content-Type: application/json

{
  "type": "SAVINGS",
  "balance": 9500.00
}

### Delete account
DELETE http://localhost:8080/accounts/4

### test deposit
GET http://localhost:8080/accounts/1
Accept: application/json
### Deposit into account
POST http://localhost:8080/accounts/1/deposit
Content-Type: application/json

{
  "amount": 500.00
}
### Invalid deposit
POST http://localhost:8080/accounts/1/deposit
Content-Type: application/json

{
  "amount": -500.00
}

### Valid withdrawal
POST http://localhost:8080/accounts/1/withdrawal
Content-Type: application/json

{
  "amount": 100.00
}

### Negative withdrawal
POST http://localhost:8080/accounts/1/withdrawal
Content-Type: application/json

{
  "amount": -100.00
}

### More than account balance
POST http://localhost:8080/accounts/1/withdrawal
Content-Type: application/json

{
  "amount": 999999.00
}

### Account doesn't exist
POST http://localhost:8080/accounts/999/withdrawal
Content-Type: application/json

{
  "amount": 100.00
}

### Get account by ID
GET http://localhost:8080/accounts/1

### Get account by ID
GET http://localhost:8080/accounts/2


### Transfer funds
POST http://localhost:8080/transfers
Content-Type: application/json

{
  "fromAccountId": 1,
  "toAccountId": 2,
  "amount": 500.00
}

### Security Check
GET http://localhost:8080/accounts

